import { randomUUID } from 'node:crypto';
import { createTestApp } from './helpers.js';
import type { EventStore, PrismaService } from '@nextera/shared';
import type { NestExpressApplication } from '@nestjs/platform-express';

/** A reading in telemetry.csv format, after the seed dataset's time range. */
const reading = (overrides: Record<string, unknown> = {}) => ({
  turbine_id: 'TURB001',
  farm_id: 'FARM01',
  timestamp: '2026-03-01T00:00:00Z',
  power_output_kw: 2331.2,
  wind_speed_ms: 8.0,
  rotor_rpm: 14.0,
  blade_pitch_deg: 3.6,
  gearbox_temp_c: 81.6,
  ...overrides,
});

const UUID_V4 =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

/** What Pub/Sub POSTs to a push endpoint. */
function push(url: string, payload: unknown, messageId: string = randomUUID()) {
  return fetch(`${url}/pubsub/telemetry`, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({
      subscription: 'projects/nextera-local/subscriptions/telemetry-ingestion',
      message: {
        messageId,
        publishTime: '2026-03-01T00:01:30Z',
        data: Buffer.from(JSON.stringify(payload)).toString('base64'),
      },
    }),
  });
}

describe('Ingestion worker (e2e, real Postgres + Redis)', () => {
  let app: NestExpressApplication;
  let url: string;
  let prisma: PrismaService;
  let events: EventStore;
  let lastEventId: string;

  beforeAll(async () => {
    ({ app, url, prisma, events } = await createTestApp());
  });

  afterAll(async () => {
    await app.close();
  });

  beforeEach(async () => {
    await prisma.$executeRaw`TRUNCATE TABLE telemetry_alerts, telemetry`;
    lastEventId = (await events.publish('test.marker', null)).id;
  });

  /** Events published to Redis since the test started (what the API streams over SSE). */
  const publishedEvents = () => events.since(lastEventId);

  it('stores a reading and publishes telemetry.received for SSE', async () => {
    const res = await push(url, reading());

    expect(res.status).toBe(204);
    const row = await prisma.telemetry.findUniqueOrThrow({
      where: {
        turbineId_timestamp: {
          turbineId: 'TURB001',
          timestamp: new Date('2026-03-01T00:00:00Z'),
        },
      },
    });
    expect(row).toMatchObject({
      farmId: 'FARM01',
      powerOutputKw: 2331.2,
      receivedAt: new Date('2026-03-01T00:01:30Z'), // Pub/Sub publish time
    });
    expect(row.id).toMatch(UUID_V4); // generated by Postgres (gen_random_uuid())

    const published = await publishedEvents();
    expect(published).toHaveLength(1);
    expect(published[0]).toMatchObject({
      type: 'telemetry.received',
      data: {
        id: row.id,
        turbineId: 'TURB001',
        timestamp: '2026-03-01T00:00:00.000Z',
      },
    });
  });

  it('keeps late-arriving readings with their real measurement time and arrival time', async () => {
    await push(
      url,
      reading({
        timestamp: '2026-03-01T00:05:00Z',
        received_at: '2026-03-01T00:30:00Z',
      }),
    );

    const row = await prisma.telemetry.findFirstOrThrow();
    expect(row.timestamp).toEqual(new Date('2026-03-01T00:05:00Z'));
    expect(row.receivedAt).toEqual(new Date('2026-03-01T00:30:00Z'));
    // created_at is the real insert time (set by Postgres), whatever received_at says.
    expect(Math.abs(row.createdAt.getTime() - Date.now())).toBeLessThan(60_000);
  });

  it('is idempotent: redeliveries and re-sent readings are acked without a second row or event', async () => {
    expect((await push(url, reading(), 'same-message')).status).toBe(204);
    expect((await push(url, reading(), 'same-message')).status).toBe(204); // redelivery
    expect((await push(url, reading({ power_output_kw: 9 }))).status).toBe(204); // re-send

    expect(await prisma.telemetry.count()).toBe(1);
    expect((await prisma.telemetry.findFirstOrThrow()).powerOutputKw).toBe(
      2331.2,
    );
    expect(await publishedEvents()).toHaveLength(1);
  });

  it('stores concurrent deliveries of one reading exactly once', async () => {
    const responses = await Promise.all(
      Array.from({ length: 10 }, () => push(url, reading())),
    );

    expect(responses.every((r) => r.status === 204)).toBe(true);
    expect(await prisma.telemetry.count()).toBe(1);
    expect(await publishedEvents()).toHaveLength(1);
  });

  it('stores abnormal readings such as the CSV’s overheating gearbox', async () => {
    expect((await push(url, reading({ gearbox_temp_c: 126.5 }))).status).toBe(
      204,
    );
    expect((await prisma.telemetry.findFirstOrThrow()).gearboxTempC).toBe(
      126.5,
    );
  });

  it('rejects an unknown turbine with 400 (dead-lettered for replay once registered)', async () => {
    const res = await push(url, reading({ turbine_id: 'TURB999' }));

    expect(res.status).toBe(400);
    expect(await prisma.telemetry.count()).toBe(0);
    expect(await publishedEvents()).toHaveLength(0);
  });

  it('rejects a reading whose farm_id is not its turbine’s farm', async () => {
    const res = await push(url, reading({ farm_id: 'FARM02' }));

    expect(res.status).toBe(400);
    expect((await res.json()).message).toBe(
      'Turbine TURB001 belongs to FARM01, not FARM02',
    );
    expect(await prisma.telemetry.count()).toBe(0);
  });

  it('enforces turbine/farm consistency in the database too (composite foreign key)', async () => {
    await expect(
      prisma.telemetry.create({
        data: {
          turbineId: 'TURB001',
          farmId: 'FARM02', // TURB001 is on FARM01
          timestamp: new Date('2026-03-01T00:00:00Z'),
          powerOutputKw: 1,
          windSpeedMs: 1,
          rotorRpm: 1,
          bladePitchDeg: 1,
          gearboxTempC: 1,
        },
      }),
    ).rejects.toMatchObject({ code: 'P2003' });
  });

  it('generates the UUID v4 id in the database when an insert bypasses Prisma', async () => {
    const [row] = await prisma.$queryRaw<{ id: string }[]>`
      INSERT INTO telemetry (turbine_id, farm_id, timestamp, power_output_kw, wind_speed_ms,
                             rotor_rpm, blade_pitch_deg, gearbox_temp_c)
      VALUES ('TURB001', 'FARM01', '2026-03-01T00:00:00Z', 1, 1, 1, 1, 1)
      RETURNING id::text`;

    expect(row.id).toMatch(UUID_V4);
  });

  it('rejects an invalid payload with 400 and stores nothing', async () => {
    const res = await push(
      url,
      reading({ power_output_kw: -5, timestamp: 'soon' }),
    );

    expect(res.status).toBe(400);
    expect(await prisma.telemetry.count()).toBe(0);
  });

  it('rejects a malformed push envelope with 400', async () => {
    const res = await fetch(`${url}/pubsub/telemetry`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ message: { data: '%%%' } }),
    });
    expect(res.status).toBe(400);
  });

  it('reports liveness and readiness', async () => {
    expect((await fetch(`${url}/health/live`)).status).toBe(200);
    const ready = await fetch(`${url}/health/ready`);
    expect(ready.status).toBe(200);
    expect((await ready.json()).details).toMatchObject({
      database: { status: 'up' },
      redis: { status: 'up' },
    });
  });

  describe('alert rules (telemetry_alerts)', () => {
    const rule = (
      valueMetric: number,
      alertLevel: 'info' | 'warn' | 'error',
      enabled = true,
    ) =>
      prisma.alertConfig.create({
        data: {
          measurementMetric: 'gearboxTempC',
          comparison: 'above',
          valueMetric,
          alertLevel,
          enabled,
        },
      });
    const alertsOf = (telemetryId: string) =>
      prisma.telemetryAlert.findMany({
        where: { telemetryId },
        include: { alert: true },
        orderBy: { alert: { valueMetric: 'asc' } },
      });

    afterEach(async () => {
      await prisma.$executeRaw`TRUNCATE TABLE telemetry_alerts, alerts_config`;
    });

    it('stores every enabled rule a reading triggers, and puts them in the live event', async () => {
      const warn = await rule(90, 'warn');
      const error = await rule(120, 'error');
      await rule(100, 'info', false); // disabled: never stored
      // Another metric, not reached (wind 8 m/s).
      await prisma.alertConfig.create({
        data: {
          measurementMetric: 'windSpeedMs',
          comparison: 'above',
          valueMetric: 25,
          alertLevel: 'error',
        },
      });

      expect((await push(url, reading({ gearbox_temp_c: 126.5 }))).status).toBe(
        204,
      );

      const stored = await prisma.telemetry.findFirstOrThrow();
      expect((await alertsOf(stored.id)).map((a) => a.alertId)).toEqual([
        warn.id,
        error.id,
      ]);
      const [event] = await publishedEvents();
      expect(
        (event.data as { alerts: { id: string }[] }).alerts.map((a) => a.id),
      ).toEqual([error.id, warn.id]); // worst first
    });

    it('stores no alert rows for a normal reading or a re-sent duplicate', async () => {
      await rule(90, 'warn');
      await push(url, reading({ gearbox_temp_c: 81.6 }));
      expect(await prisma.telemetryAlert.count()).toBe(0);

      await push(
        url,
        reading({ timestamp: '2026-03-01T00:05:00Z', gearbox_temp_c: 95 }),
      );
      await push(
        url,
        reading({ timestamp: '2026-03-01T00:05:00Z', gearbox_temp_c: 95 }),
      );
      expect(await prisma.telemetryAlert.count()).toBe(1);
    });
  });
});
